# edit this to point to the dotfiles directory
# then ln -s this file to ~/.bashrc. Done.
export DOT_FILES=$HOME/Dropbox/settings/dotfiles

. $DOT_FILES/bash/env
. $DOT_FILES/bash/config
. $DOT_FILES/bash/aliases
# if [ -f /opt/local/etc/bash_completion ]; then
# 	. /opt/local/etc/bash_completion
# else

# bash completion
if [ -f `brew --prefix`/etc/bash_completion ]; then
  . `brew --prefix`/etc/bash_completion
fi

# git completion
if [ -f $DOT_FILES/git-completion.bash ]; then
  . $DOT_FILES/git-completion.bash
fi

# git flow completion
if [ -f $DOT_FILES/git-flow-completion.bash ]; then
  . $DOT_FILES/git-flow-completion.bash
fi

# homebrew completion
if [ -f `brew --prefix`/Library/Contributions/brew_bash_completion.sh ]; then
  . `brew --prefix`/Library/Contributions/brew_bash_completion.sh
fi

# project specific aliases. Not in repo
PROJECTS=$DOT_FILES/bash/projects/*
for f in $PROJECTS
do
  echo "Sourcing: " $f
  . $f
done
